### Site Settings ###
title               : Emre Balıkçı
description         : >-                               # >- means to ignore newlines until "url:"
                      Hi! I'm Emre, a Software Engineer by day and a hobbyist by night.
latest_blog_post    : /blog/index.html
url                 : "emrebalikci.com"                         # base hostname & protocol for your site (e.g. http://example.com)
baseurl             : ""                    # subpath of your site (e.g. /blog) [IMPORTANT: use "" if your are hosting at https://username.github.io directly]
repository          : emrebalikci/emrebalikci.github.io    # repository metadata on GitHub Pages [know more at https://help.github.com/en/articles/repository-metadata-on-github-pages]
public_key             : "http://bit.ly/jieni-hou-resume-2020"
#remote_theme       : YoussefRaafatNasry/portfolYOU    # uncomment this if you are using it as a remote theme

### Author Info ###
author:
  name              : Emre Balıkçı
  image             : assets/profile.jpg
# behance           : your_username
# dribbble          : your_username
  email             : sabanemrebalikci@gmail.com
  facebook          : semrebalikci
  github            : emrebalikci
  gitlab            : emrebalikci
  instagram         : emrebalikci
  linkedin          : emrebalikci
  medium            : balikci
# soundcloud        : your_username
  spotify           : ngudu2homb9f0ot34oaz71s5t
# stackoverflow     : your_user_id
# tumblr            : your_username.tumblr.com
# twitch            : jenplaysgames2
  twitter           : emrebalikci_
# vimeo             : your_username
# youtube           : your_channel_name
  telegram          : emrebalikci


### Pagination ###
paginate: 6
paginate_path: "/blog/page-:num/"


### Posts Permalink ###
permalink: blog/:title


### Collections ###
collections:
  projects:
    output: true
    permalink: /projects/:name


### Defaults for collections ###
defaults:
  - scope:
      path: ""
      type: "projects"
    values:
      layout: "page"


### Exclude from processing ###
exclude:
- README.md
- LICENSE
- Gemfile
- Gemfile.lock